//
// Created by Jack_ on 01/09/2025.
//

#include "opcodes.h"
#include "opcodeFunctions.h"
#include "cpu.h"

 const std::unordered_map<uint8_t, opcode> opcodeTable =
	{
	    // 0x0X
	    {0x00, {"NOP", OP_NOP, AM_IMP}},
	    {0x01, {"LD", OP_LD, AM_R_D16, RT_BC}},
	    {0x02, {"LD", OP_LD, AM_MR_R, RT_BC, RT_A}},
	    {0x03, {"INC", OP_INC, AM_R, RT_BC}},
	    {0x04, {"INC", OP_INC, AM_R, RT_B}},
	    {0x05, {"DEC", OP_DEC, AM_R, RT_B}},
	    {0x06, {"LD", OP_LD, AM_R_D8, RT_B}},
	    {0x07, {"RLCA", OP_RLCA, AM_IMP}},
	    {0x08, {"LD", OP_LD, AM_A16_R, RT_NONE, RT_SP}},
	    {0x09, {"ADD", OP_ADD, AM_R_R, RT_HL, RT_BC}},
	    {0x0A, {"LD", OP_LD, AM_R_MR, RT_A, RT_BC}},
	    {0x0B, {"DEC", OP_DEC, AM_R, RT_BC}},
	    {0x0C, {"INC", OP_INC, AM_R, RT_C}},
	    {0x0D, {"DEC", OP_DEC, AM_R, RT_C}},
	    {0x0E, {"LD", OP_LD, AM_R_D8, RT_C}},
	    {0x0F, {"RRCA", OP_RRCA, AM_IMP}},

	    // 0x1X
	    {0x10, {"STOP", OP_STOP, AM_I8}},
	    {0x11, {"LD", OP_LD, AM_R_D16, RT_DE}},
	    {0x12, {"LD", OP_LD, AM_MR_R, RT_DE, RT_A}},
	    {0x13, {"INC", OP_INC, AM_R, RT_DE}},
	    {0x14, {"INC", OP_INC, AM_R, RT_D}},
	    {0x15, {"DEC", OP_DEC, AM_R, RT_D}},
	    {0x16, {"LD", OP_LD, AM_R_D8, RT_D}},
	    {0x17, {"RLA", OP_RLA, AM_IMP}},
	    {0x18, {"JR", OP_JR, AM_I8}},
	    {0x19, {"ADD", OP_ADD, AM_R_R, RT_HL, RT_DE}},
	    {0x1A, {"LD", OP_LD, AM_R_MR, RT_A, RT_DE}},
	    {0x1B, {"DEC", OP_DEC, AM_R, RT_DE}},
	    {0x1C, {"INC", OP_INC, AM_R, RT_E}},
	    {0x1D, {"DEC", OP_DEC, AM_R, RT_E}},
	    {0x1E, {"LD", OP_LD, AM_R_D8, RT_E}},
	    {0x1F, {"RRA", OP_RRA, AM_IMP}},

	    // 0x2X
	    {0x20, {"JR", OP_JR, AM_I8, RT_NONE, RT_NONE, CT_NZ}},
	    {0x21, {"LD", OP_LD, AM_R_D16, RT_HL}},
	    {0x22, {"LD", OP_LD, AM_HLI_R, RT_HL, RT_A}},
	    {0x23, {"INC", OP_INC, AM_R, RT_HL}},
	    {0x24, {"INC", OP_INC, AM_R, RT_H}},
	    {0x25, {"DEC", OP_DEC, AM_R, RT_H}},
	    {0x26, {"LD", OP_LD, AM_R_D8, RT_H}},
	    {0x27, {"DAA", OP_DAA, AM_IMP}},
	    {0x28, {"JR", OP_JR, AM_I8, RT_NONE, RT_NONE, CT_Z}},
	    {0x29, {"ADD", OP_ADD, AM_R_R, RT_HL, RT_HL}},
	    {0x2A, {"LD", OP_LD, AM_R_HLI, RT_A, RT_HL}},
	    {0x2B, {"DEC", OP_DEC, AM_R, RT_HL}},
	    {0x2C, {"INC", OP_INC, AM_R, RT_L}},
	    {0x2D, {"DEC", OP_DEC, AM_R, RT_L}},
	    {0x2E, {"LD", OP_LD, AM_R_D8, RT_L}},
	    {0x2F, {"CPL", OP_CPL, AM_IMP}},

	    // 0x3X
	    {0x30, {"JR", OP_JR, AM_I8, RT_NONE, RT_NONE, CT_NC}},
	    {0x31, {"LD", OP_LD, AM_R_D16, RT_SP}},
	    {0x32, {"LD", OP_LD, AM_HLD_R, RT_HL, RT_A}},
	    {0x33, {"INC", OP_INC, AM_R, RT_SP}},
	    {0x34, {"INC", OP_INC, AM_MR, RT_HL}},
	    {0x35, {"DEC", OP_DEC, AM_MR, RT_HL}},
	    {0x36, {"LD", OP_LD, AM_MR_D8, RT_HL}},
	    {0x37, {"SCF", OP_SCF, AM_IMP}},
	    {0x38, {"JR", OP_JR, AM_I8, RT_NONE, RT_NONE, CT_C}},
	    {0x39, {"ADD", OP_ADD, AM_R_R, RT_HL, RT_SP}},
	    {0x3A, {"LD", OP_LD, AM_R_HLD, RT_A, RT_HL}},
	    {0x3B, {"DEC", OP_DEC, AM_R, RT_SP}},
	    {0x3C, {"INC", OP_INC, AM_R, RT_A}},
	    {0x3D, {"DEC", OP_DEC, AM_R, RT_A}},
	    {0x3E, {"LD", OP_LD, AM_R_D8, RT_A}},
	    {0x3F, {"CCF", OP_CCF, AM_IMP}},

	    // 0x4X - LD B,r
	    {0x40, {"LD", OP_LD, AM_R_R, RT_B, RT_B}},
	    {0x41, {"LD", OP_LD, AM_R_R, RT_B, RT_C}},
	    {0x42, {"LD", OP_LD, AM_R_R, RT_B, RT_D}},
	    {0x43, {"LD", OP_LD, AM_R_R, RT_B, RT_E}},
	    {0x44, {"LD", OP_LD, AM_R_R, RT_B, RT_H}},
	    {0x45, {"LD", OP_LD, AM_R_R, RT_B, RT_L}},
	    {0x46, {"LD", OP_LD, AM_R_MR, RT_B, RT_HL}},
	    {0x47, {"LD", OP_LD, AM_R_R, RT_B, RT_A}},
	    {0x48, {"LD", OP_LD, AM_R_R, RT_C, RT_B}},
	    {0x49, {"LD", OP_LD, AM_R_R, RT_C, RT_C}},
	    {0x4A, {"LD", OP_LD, AM_R_R, RT_C, RT_D}},
	    {0x4B, {"LD", OP_LD, AM_R_R, RT_C, RT_E}},
	    {0x4C, {"LD", OP_LD, AM_R_R, RT_C, RT_H}},
	    {0x4D, {"LD", OP_LD, AM_R_R, RT_C, RT_L}},
	    {0x4E, {"LD", OP_LD, AM_R_MR, RT_C, RT_HL}},
	    {0x4F, {"LD", OP_LD, AM_R_R, RT_C, RT_A}},

	    // 0x5X - LD D,r
	    {0x50, {"LD", OP_LD, AM_R_R, RT_D, RT_B}},
	    {0x51, {"LD", OP_LD, AM_R_R, RT_D, RT_C}},
	    {0x52, {"LD", OP_LD, AM_R_R, RT_D, RT_D}},
	    {0x53, {"LD", OP_LD, AM_R_R, RT_D, RT_E}},
	    {0x54, {"LD", OP_LD, AM_R_R, RT_D, RT_H}},
	    {0x55, {"LD", OP_LD, AM_R_R, RT_D, RT_L}},
	    {0x56, {"LD", OP_LD, AM_R_MR, RT_D, RT_HL}},
	    {0x57, {"LD", OP_LD, AM_R_R, RT_D, RT_A}},
	    {0x58, {"LD", OP_LD, AM_R_R, RT_E, RT_B}},
	    {0x59, {"LD", OP_LD, AM_R_R, RT_E, RT_C}},
	    {0x5A, {"LD", OP_LD, AM_R_R, RT_E, RT_D}},
	    {0x5B, {"LD", OP_LD, AM_R_R, RT_E, RT_E}},
	    {0x5C, {"LD", OP_LD, AM_R_R, RT_E, RT_H}},
	    {0x5D, {"LD", OP_LD, AM_R_R, RT_E, RT_L}},
	    {0x5E, {"LD", OP_LD, AM_R_MR, RT_E, RT_HL}},
	    {0x5F, {"LD", OP_LD, AM_R_R, RT_E, RT_A}},

	    // 0x6X - LD H,r
	    {0x60, {"LD", OP_LD, AM_R_R, RT_H, RT_B}},
	    {0x61, {"LD", OP_LD, AM_R_R, RT_H, RT_C}},
	    {0x62, {"LD", OP_LD, AM_R_R, RT_H, RT_D}},
	    {0x63, {"LD", OP_LD, AM_R_R, RT_H, RT_E}},
	    {0x64, {"LD", OP_LD, AM_R_R, RT_H, RT_H}},
	    {0x65, {"LD", OP_LD, AM_R_R, RT_H, RT_L}},
	    {0x66, {"LD", OP_LD, AM_R_MR, RT_H, RT_HL}},
	    {0x67, {"LD", OP_LD, AM_R_R, RT_H, RT_A}},
	    {0x68, {"LD", OP_LD, AM_R_R, RT_L, RT_B}},
	    {0x69, {"LD", OP_LD, AM_R_R, RT_L, RT_C}},
	    {0x6A, {"LD", OP_LD, AM_R_R, RT_L, RT_D}},
	    {0x6B, {"LD", OP_LD, AM_R_R, RT_L, RT_E}},
	    {0x6C, {"LD", OP_LD, AM_R_R, RT_L, RT_H}},
	    {0x6D, {"LD", OP_LD, AM_R_R, RT_L, RT_L}},
	    {0x6E, {"LD", OP_LD, AM_R_MR, RT_L, RT_HL}},
	    {0x6F, {"LD", OP_LD, AM_R_R, RT_L, RT_A}},

	    // 0x7X - LD (HL),r and LD A,r
	    {0x70, {"LD", OP_LD, AM_MR_R, RT_HL, RT_B}},
	    {0x71, {"LD", OP_LD, AM_MR_R, RT_HL, RT_C}},
	    {0x72, {"LD", OP_LD, AM_MR_R, RT_HL, RT_D}},
	    {0x73, {"LD", OP_LD, AM_MR_R, RT_HL, RT_E}},
	    {0x74, {"LD", OP_LD, AM_MR_R, RT_HL, RT_H}},
	    {0x75, {"LD", OP_LD, AM_MR_R, RT_HL, RT_L}},
	    {0x76, {"HALT", OP_HALT, AM_IMP}},
	    {0x77, {"LD", OP_LD, AM_MR_R, RT_HL, RT_A}},
	    {0x78, {"LD", OP_LD, AM_R_R, RT_A, RT_B}},
	    {0x79, {"LD", OP_LD, AM_R_R, RT_A, RT_C}},
	    {0x7A, {"LD", OP_LD, AM_R_R, RT_A, RT_D}},
	    {0x7B, {"LD", OP_LD, AM_R_R, RT_A, RT_E}},
	    {0x7C, {"LD", OP_LD, AM_R_R, RT_A, RT_H}},
	    {0x7D, {"LD", OP_LD, AM_R_R, RT_A, RT_L}},
	    {0x7E, {"LD", OP_LD, AM_R_MR, RT_A, RT_HL}},
	    {0x7F, {"LD", OP_LD, AM_R_R, RT_A, RT_A}},

	    // 0x8X - ADD A,r
	    {0x80, {"ADD", OP_ADD, AM_R_R, RT_A, RT_B}},
	    {0x81, {"ADD", OP_ADD, AM_R_R, RT_A, RT_C}},
	    {0x82, {"ADD", OP_ADD, AM_R_R, RT_A, RT_D}},
	    {0x83, {"ADD", OP_ADD, AM_R_R, RT_A, RT_E}},
	    {0x84, {"ADD", OP_ADD, AM_R_R, RT_A, RT_H}},
	    {0x85, {"ADD", OP_ADD, AM_R_R, RT_A, RT_L}},
	    {0x86, {"ADD", OP_ADD, AM_R_MR, RT_A, RT_HL}},
	    {0x87, {"ADD", OP_ADD, AM_R_R, RT_A, RT_A}},
	    {0x88, {"ADC", OP_ADC, AM_R_R, RT_A, RT_B}},
	    {0x89, {"ADC", OP_ADC, AM_R_R, RT_A, RT_C}},
	    {0x8A, {"ADC", OP_ADC, AM_R_R, RT_A, RT_D}},
	    {0x8B, {"ADC", OP_ADC, AM_R_R, RT_A, RT_E}},
	    {0x8C, {"ADC", OP_ADC, AM_R_R, RT_A, RT_H}},
	    {0x8D, {"ADC", OP_ADC, AM_R_R, RT_A, RT_L}},
	    {0x8E, {"ADC", OP_ADC, AM_R_MR, RT_A, RT_HL}},
	    {0x8F, {"ADC", OP_ADC, AM_R_R, RT_A, RT_A}},

	    // 0x9X - SUB r
	    {0x90, {"SUB", OP_SUB, AM_R_R, RT_A, RT_B}},
	    {0x91, {"SUB", OP_SUB, AM_R_R, RT_A, RT_C}},
	    {0x92, {"SUB", OP_SUB, AM_R_R, RT_A, RT_D}},
	    {0x93, {"SUB", OP_SUB, AM_R_R, RT_A, RT_E}},
	    {0x94, {"SUB", OP_SUB, AM_R_R, RT_A, RT_H}},
	    {0x95, {"SUB", OP_SUB, AM_R_R, RT_A, RT_L}},
	    {0x96, {"SUB", OP_SUB, AM_R_MR, RT_A, RT_HL}},
	    {0x97, {"SUB", OP_SUB, AM_R_R, RT_A, RT_A}},
	    {0x98, {"SBC", OP_SBC, AM_R_R, RT_A, RT_B}},
	    {0x99, {"SBC", OP_SBC, AM_R_R, RT_A, RT_C}},
	    {0x9A, {"SBC", OP_SBC, AM_R_R, RT_A, RT_D}},
	    {0x9B, {"SBC", OP_SBC, AM_R_R, RT_A, RT_E}},
	    {0x9C, {"SBC", OP_SBC, AM_R_R, RT_A, RT_H}},
	    {0x9D, {"SBC", OP_SBC, AM_R_R, RT_A, RT_L}},
	    {0x9E, {"SBC", OP_SBC, AM_R_MR, RT_A, RT_HL}},
	    {0x9F, {"SBC", OP_SBC, AM_R_R, RT_A, RT_A}},

	    // 0xAX - AND r
	    {0xA0, {"AND", OP_AND, AM_R_R, RT_A, RT_B}},
	    {0xA1, {"AND", OP_AND, AM_R_R, RT_A, RT_C}},
	    {0xA2, {"AND", OP_AND, AM_R_R, RT_A, RT_D}},
	    {0xA3, {"AND", OP_AND, AM_R_R, RT_A, RT_E}},
	    {0xA4, {"AND", OP_AND, AM_R_R, RT_A, RT_H}},
	    {0xA5, {"AND", OP_AND, AM_R_R, RT_A, RT_L}},
	    {0xA6, {"AND", OP_AND, AM_R_MR, RT_A, RT_HL}},
	    {0xA7, {"AND", OP_AND, AM_R_R, RT_A, RT_A}},
	    {0xA8, {"XOR", OP_XOR, AM_R_R, RT_A, RT_B}},
	    {0xA9, {"XOR", OP_XOR, AM_R_R, RT_A, RT_C}},
	    {0xAA, {"XOR", OP_XOR, AM_R_R, RT_A, RT_D}},
	    {0xAB, {"XOR", OP_XOR, AM_R_R, RT_A, RT_E}},
	    {0xAC, {"XOR", OP_XOR, AM_R_R, RT_A, RT_H}},
	    {0xAD, {"XOR", OP_XOR, AM_R_R, RT_A, RT_L}},
	    {0xAE, {"XOR", OP_XOR, AM_R_MR, RT_A, RT_HL}},
	    {0xAF, {"XOR", OP_XOR, AM_R_R, RT_A, RT_A}},

	    // 0xBX - OR r and CP r
	    {0xB0, {"OR", OP_OR, AM_R_R, RT_A, RT_B}},
	    {0xB1, {"OR", OP_OR, AM_R_R, RT_A, RT_C}},
	    {0xB2, {"OR", OP_OR, AM_R_R, RT_A, RT_D}},
	    {0xB3, {"OR", OP_OR, AM_R_R, RT_A, RT_E}},
	    {0xB4, {"OR", OP_OR, AM_R_R, RT_A, RT_H}},
	    {0xB5, {"OR", OP_OR, AM_R_R, RT_A, RT_L}},
	    {0xB6, {"OR", OP_OR, AM_R_MR, RT_A, RT_HL}},
	    {0xB7, {"OR", OP_OR, AM_R_R, RT_A, RT_A}},
	    {0xB8, {"CP", OP_CP, AM_R_R, RT_A, RT_B}},
	    {0xB9, {"CP", OP_CP, AM_R_R, RT_A, RT_C}},
	    {0xBA, {"CP", OP_CP, AM_R_R, RT_A, RT_D}},
	    {0xBB, {"CP", OP_CP, AM_R_R, RT_A, RT_E}},
	    {0xBC, {"CP", OP_CP, AM_R_R, RT_A, RT_H}},
	    {0xBD, {"CP", OP_CP, AM_R_R, RT_A, RT_L}},
	    {0xBE, {"CP", OP_CP, AM_R_MR, RT_A, RT_HL}},
	    {0xBF, {"CP", OP_CP, AM_R_R, RT_A, RT_A}},

	    // 0xCX
	    {0xC0, {"RET", OP_RET, AM_IMP, RT_NONE, RT_NONE, CT_NZ}},
	    {0xC1, {"POP", OP_POP, AM_R, RT_BC}},
	    {0xC2, {"JP", OP_JP, AM_I16, RT_NONE, RT_NONE, CT_NZ}},
	    {0xC3, {"JP", OP_JP, AM_I16}},
	    {0xC4, {"CALL", OP_CALL, AM_I16, RT_NONE, RT_NONE, CT_NZ}},
	    {0xC5, {"PUSH", OP_PUSH, AM_R, RT_BC}},
	    {0xC6, {"ADD", OP_ADD, AM_R_D8, RT_A}},
	    {0xC7, {"RST", OP_RST, AM_IMP, RT_NONE, RT_NONE, CT_NONE, 0x00}},
	    {0xC8, {"RET", OP_RET, AM_IMP, RT_NONE, RT_NONE, CT_Z}},
	    {0xC9, {"RET", OP_RET, AM_IMP}},
	    {0xCA, {"JP", OP_JP, AM_I16, RT_NONE, RT_NONE, CT_Z}},
	    {0xCB, {"CB", OP_CB, AM_I8}},
	    {0xCC, {"CALL", OP_CALL, AM_I16, RT_NONE, RT_NONE, CT_Z}},
	    {0xCD, {"CALL", OP_CALL, AM_I16}},
	    {0xCE, {"ADC", OP_ADC, AM_R_D8, RT_A}},
	    {0xCF, {"RST", OP_RST, AM_IMP, RT_NONE, RT_NONE, CT_NONE, 0x08}},

	    // 0xDX
	    {0xD0, {"RET", OP_RET, AM_IMP, RT_NONE, RT_NONE, CT_NC}},
	    {0xD1, {"POP", OP_POP, AM_R, RT_DE}},
	    {0xD2, {"JP", OP_JP, AM_I16, RT_NONE, RT_NONE, CT_NC}},
	    {0xD4, {"CALL", OP_CALL, AM_I16, RT_NONE, RT_NONE, CT_NC}},
	    {0xD5, {"PUSH", OP_PUSH, AM_R, RT_DE}},
	    {0xD6, {"SUB", OP_SUB, AM_R_D8, RT_A}},
	    {0xD7, {"RST", OP_RST, AM_IMP, RT_NONE, RT_NONE, CT_NONE, 0x10}},
	    {0xD8, {"RET", OP_RET, AM_IMP, RT_NONE, RT_NONE, CT_C}},
	    {0xD9, {"RETI", OP_RETI, AM_IMP}},
	    {0xDA, {"JP", OP_JP, AM_I16, RT_NONE, RT_NONE, CT_C}},
	    {0xDC, {"CALL", OP_CALL, AM_I16, RT_NONE, RT_NONE, CT_C}},
	    {0xDE, {"SBC", OP_SBC, AM_R_D8, RT_A}},
	    {0xDF, {"RST", OP_RST, AM_IMP, RT_NONE, RT_NONE, CT_NONE, 0x18}},

	    // 0xEX
	    {0xE0, {"LDH", OP_LDH, AM_A8_R, RT_NONE, RT_A}},
	    {0xE1, {"POP", OP_POP, AM_R, RT_HL}},
	    {0xE2, {"LD", OP_LD, AM_MR_R, RT_C, RT_A}},
	    {0xE5, {"PUSH", OP_PUSH, AM_R, RT_HL}},
	    {0xE6, {"AND", OP_AND, AM_R_D8, RT_A}},
	    {0xE7, {"RST", OP_RST, AM_IMP, RT_NONE, RT_NONE, CT_NONE, 0x20}},
	    {0xE8, {"ADD", OP_ADD, AM_R_D8, RT_SP}},
	    {0xE9, {"JPHL", OP_JPHL, AM_R}},
	    {0xEA, {"LD", OP_LD, AM_A16_R, RT_NONE, RT_A}},
	    {0xEE, {"XOR", OP_XOR, AM_R_D8, RT_A}},
	    {0xEF, {"RST", OP_RST, AM_IMP, RT_NONE, RT_NONE, CT_NONE, 0x28}},

	    // 0xFX
	    {0xF0, {"LDH", OP_LDH, AM_R_A8, RT_A}},
	    {0xF1, {"POP", OP_POP, AM_R, RT_AF}},
	    {0xF2, {"LD", OP_LD, AM_R_MR, RT_A, RT_C}},
	    {0xF3, {"DI", OP_DI, AM_IMP}},
	    {0xF5, {"PUSH", OP_PUSH, AM_R, RT_AF}},
	    {0xF6, {"OR", OP_OR, AM_R_D8, RT_A}},
	    {0xF7, {"RST", OP_RST, AM_IMP, RT_NONE, RT_NONE, CT_NONE, 0x30}},
	    {0xF8, {"LD", OP_LD, AM_HL_SPR, RT_HL, RT_SP}},
	    {0xF9, {"LD", OP_LD, AM_R_R, RT_SP, RT_HL}},
	    {0xFA, {"LD", OP_LD, AM_R_A16, RT_A}},
	    {0xFB, {"EI", OP_EI, AM_IMP}},
	    {0xFE, {"CP", OP_CP, AM_R_D8, RT_A}},
	    {0xFF, {"RST", OP_RST, AM_IMP, RT_NONE, RT_NONE, CT_NONE, 0x38}}
	};


const std::unordered_map<uint8_t, extendedCBOpcode> cbOpcodeTable =
{
    // 0x0X - RLC r
    {0x00, {"RLC", OP_RLC, RT_B}},
    {0x01, {"RLC", OP_RLC, RT_C}},
    {0x02, {"RLC", OP_RLC, RT_D}},
    {0x03, {"RLC", OP_RLC, RT_E}},
    {0x04, {"RLC", OP_RLC, RT_H}},
    {0x05, {"RLC", OP_RLC, RT_L}},
    {0x06, {"RLC", OP_RLC, RT_HL}},
    {0x07, {"RLC", OP_RLC, RT_A}},
    {0x08, {"RRC", OP_RRC, RT_B}},
    {0x09, {"RRC", OP_RRC, RT_C}},
    {0x0A, {"RRC", OP_RRC, RT_D}},
    {0x0B, {"RRC", OP_RRC, RT_E}},
    {0x0C, {"RRC", OP_RRC, RT_H}},
    {0x0D, {"RRC", OP_RRC, RT_L}},
    {0x0E, {"RRC", OP_RRC, RT_HL}},
    {0x0F, {"RRC", OP_RRC, RT_A}},

    // 0x1X - RL r and RR r
    {0x10, {"RL", OP_RL, RT_B}},
    {0x11, {"RL", OP_RL, RT_C}},
    {0x12, {"RL", OP_RL, RT_D}},
    {0x13, {"RL", OP_RL, RT_E}},
    {0x14, {"RL", OP_RL, RT_H}},
    {0x15, {"RL", OP_RL, RT_L}},
    {0x16, {"RL", OP_RL, RT_HL}},
    {0x17, {"RL", OP_RL, RT_A}},
    {0x18, {"RR", OP_RR, RT_B}},
    {0x19, {"RR", OP_RR, RT_C}},
    {0x1A, {"RR", OP_RR, RT_D}},
    {0x1B, {"RR", OP_RR, RT_E}},
    {0x1C, {"RR", OP_RR, RT_H}},
    {0x1D, {"RR", OP_RR, RT_L}},
    {0x1E, {"RR", OP_RR, RT_HL}},
    {0x1F, {"RR", OP_RR, RT_A}},

    // 0x2X - SLA r and SRA r
    {0x20, {"SLA", OP_SLA, RT_B}},
    {0x21, {"SLA", OP_SLA, RT_C}},
    {0x22, {"SLA", OP_SLA, RT_D}},
    {0x23, {"SLA", OP_SLA, RT_E}},
    {0x24, {"SLA", OP_SLA, RT_H}},
    {0x25, {"SLA", OP_SLA, RT_L}},
    {0x26, {"SLA", OP_SLA, RT_HL}},
    {0x27, {"SLA", OP_SLA, RT_A}},
    {0x28, {"SRA", OP_SRA, RT_B}},
    {0x29, {"SRA", OP_SRA, RT_C}},
    {0x2A, {"SRA", OP_SRA, RT_D}},
    {0x2B, {"SRA", OP_SRA, RT_E}},
    {0x2C, {"SRA", OP_SRA, RT_H}},
    {0x2D, {"SRA", OP_SRA, RT_L}},
    {0x2E, {"SRA", OP_SRA, RT_HL}},
    {0x2F, {"SRA", OP_SRA, RT_A}},

    // 0x3X - SWAP r and SRL r
    {0x30, {"SWAP", OP_SWAP, RT_B}},
    {0x31, {"SWAP", OP_SWAP, RT_C}},
    {0x32, {"SWAP", OP_SWAP, RT_D}},
    {0x33, {"SWAP", OP_SWAP, RT_E}},
    {0x34, {"SWAP", OP_SWAP, RT_H}},
    {0x35, {"SWAP", OP_SWAP, RT_L}},
    {0x36, {"SWAP", OP_SWAP, RT_HL}},
    {0x37, {"SWAP", OP_SWAP, RT_A}},
    {0x38, {"SRL", OP_SRL, RT_B}},
    {0x39, {"SRL", OP_SRL, RT_C}},
    {0x3A, {"SRL", OP_SRL, RT_D}},
    {0x3B, {"SRL", OP_SRL, RT_E}},
    {0x3C, {"SRL", OP_SRL, RT_H}},
    {0x3D, {"SRL", OP_SRL, RT_L}},
    {0x3E, {"SRL", OP_SRL, RT_HL}},
    {0x3F, {"SRL", OP_SRL, RT_A}},

    // 0x4X - BIT 0,r
    {0x40, {"BIT", OP_BIT, RT_B}},
    {0x41, {"BIT", OP_BIT, RT_C}},
    {0x42, {"BIT", OP_BIT, RT_D}},
    {0x43, {"BIT", OP_BIT, RT_E}},
    {0x44, {"BIT", OP_BIT, RT_H}},
    {0x45, {"BIT", OP_BIT, RT_L}},
    {0x46, {"BIT", OP_BIT, RT_HL}},
    {0x47, {"BIT", OP_BIT, RT_A}},
    {0x48, {"BIT", OP_BIT, RT_B}},
    {0x49, {"BIT", OP_BIT, RT_C}},
    {0x4A, {"BIT", OP_BIT, RT_D}},
    {0x4B, {"BIT", OP_BIT, RT_E}},
    {0x4C, {"BIT", OP_BIT, RT_H}},
    {0x4D, {"BIT", OP_BIT, RT_L}},
    {0x4E, {"BIT", OP_BIT, RT_HL}},
    {0x4F, {"BIT", OP_BIT, RT_A}},

    // 0x5X - BIT 2,r and BIT 3,r
    {0x50, {"BIT", OP_BIT, RT_B}},
    {0x51, {"BIT", OP_BIT, RT_C}},
    {0x52, {"BIT", OP_BIT, RT_D}},
    {0x53, {"BIT", OP_BIT, RT_E}},
    {0x54, {"BIT", OP_BIT, RT_H}},
    {0x55, {"BIT", OP_BIT, RT_L}},
    {0x56, {"BIT", OP_BIT, RT_HL}},
    {0x57, {"BIT", OP_BIT, RT_A}},
    {0x58, {"BIT", OP_BIT, RT_B}},
    {0x59, {"BIT", OP_BIT, RT_C}},
    {0x5A, {"BIT", OP_BIT, RT_D}},
    {0x5B, {"BIT", OP_BIT, RT_E}},
    {0x5C, {"BIT", OP_BIT, RT_H}},
    {0x5D, {"BIT", OP_BIT, RT_L}},
    {0x5E, {"BIT", OP_BIT, RT_HL}},
    {0x5F, {"BIT", OP_BIT, RT_A}},

    // 0x6X - BIT 4,r and BIT 5,r
    {0x60, {"BIT", OP_BIT, RT_B}},
    {0x61, {"BIT", OP_BIT, RT_C}},
    {0x62, {"BIT", OP_BIT, RT_D}},
    {0x63, {"BIT", OP_BIT, RT_E}},
    {0x64, {"BIT", OP_BIT, RT_H}},
    {0x65, {"BIT", OP_BIT, RT_L}},
    {0x66, {"BIT", OP_BIT, RT_HL}},
    {0x67, {"BIT", OP_BIT, RT_A}},
    {0x68, {"BIT", OP_BIT, RT_B}},
    {0x69, {"BIT", OP_BIT, RT_C}},
    {0x6A, {"BIT", OP_BIT, RT_D}},
    {0x6B, {"BIT", OP_BIT, RT_E}},
    {0x6C, {"BIT", OP_BIT, RT_H}},
    {0x6D, {"BIT", OP_BIT, RT_L}},
    {0x6E, {"BIT", OP_BIT, RT_HL}},
    {0x6F, {"BIT", OP_BIT, RT_A}},

    // 0x7X - BIT 6,r and BIT 7,r
    {0x70, {"BIT", OP_BIT, RT_B}},
    {0x71, {"BIT", OP_BIT, RT_C}},
    {0x72, {"BIT", OP_BIT, RT_D}},
    {0x73, {"BIT", OP_BIT, RT_E}},
    {0x74, {"BIT", OP_BIT, RT_H}},
    {0x75, {"BIT", OP_BIT, RT_L}},
    {0x76, {"BIT", OP_BIT, RT_HL}},
    {0x77, {"BIT", OP_BIT, RT_A}},
    {0x78, {"BIT", OP_BIT, RT_B}},
    {0x79, {"BIT", OP_BIT, RT_C}},
    {0x7A, {"BIT", OP_BIT, RT_D}},
    {0x7B, {"BIT", OP_BIT, RT_E}},
    {0x7C, {"BIT", OP_BIT, RT_H}},
    {0x7D, {"BIT", OP_BIT, RT_L}},
    {0x7E, {"BIT", OP_BIT, RT_HL}},
    {0x7F, {"BIT", OP_BIT, RT_A}},

    // 0x8X - RES 0,r and RES 1,r
    {0x80, {"RES", OP_RES, RT_B}},
    {0x81, {"RES", OP_RES, RT_C}},
    {0x82, {"RES", OP_RES, RT_D}},
    {0x83, {"RES", OP_RES, RT_E}},
    {0x84, {"RES", OP_RES, RT_H}},
    {0x85, {"RES", OP_RES, RT_L}},
    {0x86, {"RES", OP_RES, RT_HL}},
    {0x87, {"RES", OP_RES, RT_A}},
    {0x88, {"RES", OP_RES, RT_B}},
    {0x89, {"RES", OP_RES, RT_C}},
    {0x8A, {"RES", OP_RES, RT_D}},
    {0x8B, {"RES", OP_RES, RT_E}},
    {0x8C, {"RES", OP_RES, RT_H}},
    {0x8D, {"RES", OP_RES, RT_L}},
    {0x8E, {"RES", OP_RES, RT_HL}},
    {0x8F, {"RES", OP_RES, RT_A}},

    // 0x9X - RES 2,r and RES 3,r
    {0x90, {"RES", OP_RES, RT_B}},
    {0x91, {"RES", OP_RES, RT_C}},
    {0x92, {"RES", OP_RES, RT_D}},
    {0x93, {"RES", OP_RES, RT_E}},
    {0x94, {"RES", OP_RES, RT_H}},
    {0x95, {"RES", OP_RES, RT_L}},
    {0x96, {"RES", OP_RES, RT_HL}},
    {0x97, {"RES", OP_RES, RT_A}},
    {0x98, {"RES", OP_RES, RT_B}},
    {0x99, {"RES", OP_RES, RT_C}},
    {0x9A, {"RES", OP_RES, RT_D}},
    {0x9B, {"RES", OP_RES, RT_E}},
    {0x9C, {"RES", OP_RES, RT_H}},
    {0x9D, {"RES", OP_RES, RT_L}},
    {0x9E, {"RES", OP_RES, RT_HL}},
    {0x9F, {"RES", OP_RES, RT_A}},

    // 0xAX - RES 4,r and RES 5,r
    {0xA0, {"RES", OP_RES, RT_B}},
    {0xA1, {"RES", OP_RES, RT_C}},
    {0xA2, {"RES", OP_RES, RT_D}},
    {0xA3, {"RES", OP_RES, RT_E}},
    {0xA4, {"RES", OP_RES, RT_H}},
    {0xA5, {"RES", OP_RES, RT_L}},
    {0xA6, {"RES", OP_RES, RT_HL}},
    {0xA7, {"RES", OP_RES, RT_A}},
    {0xA8, {"RES", OP_RES, RT_B}},
    {0xA9, {"RES", OP_RES, RT_C}},
    {0xAA, {"RES", OP_RES, RT_D}},
    {0xAB, {"RES", OP_RES, RT_E}},
    {0xAC, {"RES", OP_RES, RT_H}},
    {0xAD, {"RES", OP_RES, RT_L}},
    {0xAE, {"RES", OP_RES, RT_HL}},
    {0xAF, {"RES", OP_RES, RT_A}},

    // 0xBX - RES 6,r and RES 7,r
    {0xB0, {"RES", OP_RES, RT_B}},
    {0xB1, {"RES", OP_RES, RT_C}},
    {0xB2, {"RES", OP_RES, RT_D}},
    {0xB3, {"RES", OP_RES, RT_E}},
    {0xB4, {"RES", OP_RES, RT_H}},
    {0xB5, {"RES", OP_RES, RT_L}},
    {0xB6, {"RES", OP_RES, RT_HL}},
    {0xB7, {"RES", OP_RES, RT_A}},
    {0xB8, {"RES", OP_RES, RT_B}},
    {0xB9, {"RES", OP_RES, RT_C}},
    {0xBA, {"RES", OP_RES, RT_D}},
    {0xBB, {"RES", OP_RES, RT_E}},
    {0xBC, {"RES", OP_RES, RT_H}},
    {0xBD, {"RES", OP_RES, RT_L}},
    {0xBE, {"RES", OP_RES, RT_HL}},
    {0xBF, {"RES", OP_RES, RT_A}},

    // 0xCX - SET 0,r and SET 1,r
    {0xC0, {"SET", OP_SET, RT_B}},
    {0xC1, {"SET", OP_SET, RT_C}},
    {0xC2, {"SET", OP_SET, RT_D}},
    {0xC3, {"SET", OP_SET, RT_E}},
    {0xC4, {"SET", OP_SET, RT_H}},
    {0xC5, {"SET", OP_SET, RT_L}},
    {0xC6, {"SET", OP_SET, RT_HL}},
    {0xC7, {"SET", OP_SET, RT_A}},
    {0xC8, {"SET", OP_SET, RT_B}},
    {0xC9, {"SET", OP_SET, RT_C}},
    {0xCA, {"SET", OP_SET, RT_D}},
    {0xCB, {"SET", OP_SET, RT_E}},
    {0xCC, {"SET", OP_SET, RT_H}},
    {0xCD, {"SET", OP_SET, RT_L}},
    {0xCE, {"SET", OP_SET, RT_HL}},
    {0xCF, {"SET", OP_SET, RT_A}},

    // 0xDX - SET 2,r and SET 3,r
    {0xD0, {"SET", OP_SET, RT_B}},
    {0xD1, {"SET", OP_SET, RT_C}},
    {0xD2, {"SET", OP_SET, RT_D}},
    {0xD3, {"SET", OP_SET, RT_E}},
    {0xD4, {"SET", OP_SET, RT_H}},
    {0xD5, {"SET", OP_SET, RT_L}},
    {0xD6, {"SET", OP_SET, RT_HL}},
    {0xD7, {"SET", OP_SET, RT_A}},
    {0xD8, {"SET", OP_SET, RT_B}},
    {0xD9, {"SET", OP_SET, RT_C}},
    {0xDA, {"SET", OP_SET, RT_D}},
    {0xDB, {"SET", OP_SET, RT_E}},
    {0xDC, {"SET", OP_SET, RT_H}},
    {0xDD, {"SET", OP_SET, RT_L}},
    {0xDE, {"SET", OP_SET, RT_HL}},
    {0xDF, {"SET", OP_SET, RT_A}},

    // 0xEX - SET 4,r and SET 5,r
    {0xE0, {"SET", OP_SET, RT_B}},
    {0xE1, {"SET", OP_SET, RT_C}},
    {0xE2, {"SET", OP_SET, RT_D}},
    {0xE3, {"SET", OP_SET, RT_E}},
    {0xE4, {"SET", OP_SET, RT_H}},
    {0xE5, {"SET", OP_SET, RT_L}},
    {0xE6, {"SET", OP_SET, RT_HL}},
    {0xE7, {"SET", OP_SET, RT_A}},
    {0xE8, {"SET", OP_SET, RT_B}},
    {0xE9, {"SET", OP_SET, RT_C}},
    {0xEA, {"SET", OP_SET, RT_D}},
    {0xEB, {"SET", OP_SET, RT_E}},
    {0xEC, {"SET", OP_SET, RT_H}},
    {0xED, {"SET", OP_SET, RT_L}},
    {0xEE, {"SET", OP_SET, RT_HL}},
    {0xEF, {"SET", OP_SET, RT_A}},

    // 0xFX - SET 6,r and SET 7,r
    {0xF0, {"SET", OP_SET, RT_B}},
    {0xF1, {"SET", OP_SET, RT_C}},
    {0xF2, {"SET", OP_SET, RT_D}},
    {0xF3, {"SET", OP_SET, RT_E}},
    {0xF4, {"SET", OP_SET, RT_H}},
    {0xF5, {"SET", OP_SET, RT_L}},
    {0xF6, {"SET", OP_SET, RT_HL}},
    {0xF7, {"SET", OP_SET, RT_A}},
    {0xF8, {"SET", OP_SET, RT_B}},
    {0xF9, {"SET", OP_SET, RT_C}},
    {0xFA, {"SET", OP_SET, RT_D}},
    {0xFB, {"SET", OP_SET, RT_E}},
    {0xFC, {"SET", OP_SET, RT_H}},
    {0xFD, {"SET", OP_SET, RT_L}},
    {0xFE, {"SET", OP_SET, RT_HL}},
    {0xFF, {"SET", OP_SET, RT_A}},

};



// Initialize execute functions after map creation
void initializeOpcodeExecution() {
	static bool initialized = false;
	if (initialized) return;

	// Cast away const for initialization - done once at startup
	auto& mutable_opcodes = const_cast<std::unordered_map<uint8_t, opcode>&>(opcodeTable);

	for (auto& [opcode_value, op] : mutable_opcodes) {
		op.execute = [opcodeData = op](cpu& c) {
			if (const auto cmd = OpcodeCommandFactory::createCommand(opcodeData)) {
				cmd->execute(c);
			}
		};
	}
	initialized = true;
}

opcode getOpcode(const uint8_t opcode_value) {
	initializeOpcodeExecution();
	const auto it = opcodeTable.find(opcode_value);
	return (it != opcodeTable.end()) ? it->second : opcodeTable.at(0); // fallback to NOP
}

extendedCBOpcode getCBOpcode(const uint8_t opcode_value)
{
	const auto it = cbOpcodeTable.find(opcode_value);
	return (it != cbOpcodeTable.end()) ? it->second : extendedCBOpcode();
}
